import pandas as pd
from dotenv import load_dotenv
from gpt import Gpt3
import os
import argparse
load_dotenv()

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--percent", help="Muestra porcentaje de las respuestas", action="store_true")
    parser.add_argument("-l", "--load", help="Carga datos si existio algun error en el codigo", action="store_true")
    args = parser.parse_args()

    minimo = 0
    maximo = 916
    # file_corpus_train = "corpus/lcp_single_train_arreglo_escala.xlsx"
    # file_corpus_test = "docs/corpus/test_depurado.xlsx"

    # file_corpus_train = "docs/corpus/clexis/clexis_match_complete_format.xlsx"
    # file_corpus_train = "docs/corpus/legalEC/legalEC_ejecutar_clear.xlsx"
    file_corpus_train = "docs/corpus/AdminLex/AdminLex_final.xlsx"


    prompt = {
        "prompt_diff_source_Clexis": "Instructions: This is a complex word classification task and there is a set of texts from different subjects in computational studies, each text contains one complex word. Your task is to generate the level of complexity of the complex word in each text on a scale of 0 to 1, where 0 indicates that the word is very easy and 1 indicates that the word is very difficult.\n\nExample:\n\nSubject: Contabilidad\nSentence: \"texto 5 de ahí nosotros tenemos lo que es contabilidad y nosotros manejamos en hogares, empresas en el mercado, todo el mundo manejan lo que es contabilidad, porque hacen el registro verdad, de todos sus hechos económicos dentro de una libretita, la notación.\"\nComplex word: mercado\nComplexity level of the complex word: 0.2\n\nSource text: Comportamiento Organizacional  y Talento Humano\nSentence: \"Los apático: tienden a sumergirse en un estado de Gran melancolía.\"\nComplex word: melancolía\nComplexity level of the complex word: 0.2\n\nSource text: Base de datos II\nSentence: \"Algunas extensiones populares de archivos de base de datos son: DB, MDB, ITDB, y DBF.\"\nComplex word: db\nComplexity level of the complex word: 0.4\n\nSource text: Auditoria de Sistemas\nSentence: \"texto 56 LA ENTREVISTA La entrevista es una situación de interrelación o diálogo entre personas, el entrevistador y el entrevistado.\"   \nComplex word: interrelación\nComplexity level of the complex word: 0.4\n\nSource text: Matemática Financiera\nSentence: \"texto 59 La tasa de corte del VAN puede ser: El interés que se tenga en el mercado.\"\nComplex word: interés\nComplexity level of the complex word: 0.6\n\nSource text: Organización y Arquitectura Computacional\nSentence: \"Existe un tiempo de lectura, de decodificación y un tiempo de ejecución.\"\nComplex word: decodificación\nComplexity level of the complex word: 0.6\n\nSource text: Democracia\nSentence: \"Luego, aquí tenemos cosas prieta que nosotros tenemos, ejercemos nuestra soberanía, toda la independencia y no se admiten injerencia de otros países.\"\nComplex word: injerencia\nComplexity level of the complex word: 0.8\n\nSource text: Auditoria de Sistemas\nSentence: \"Rendimiento (Throughput): Número de procesos terminados por unidad de tiempo\"\nComplex word: throughput\nComplexity level of the complex word: 1\n\n[Response]\n\nSource text: @recurso\nSentence: @oracion\nComplex word: @aEvaluar\nComplexity level of the complex word: [Response]",
        "prompt_same_source_bi": "Word Difficulty Classification Task\n\nSource of the text: biomed, biblia, europarl\n\nInstructions: Below are a series of sentences, each containing a complex word. Your task is to generate the Complexity level of the complex word in each sentence on a scale from 0 to 1, where 0 indicates the word is very easy, and 1 indicates the word is very difficult.\n\nExample:\n\nSource text: bible\nSentence: \"You that are full of shouting, a tumultuous city, a joyous town; your slain are not slain with the sword, neither are they dead in battle.\"\nComplex word: battle\nComplexity level of the complex word: 0.30\n\nSource text: bible\nSentence: \"I desire therefore that the men in every place pray, lifting up holy hands without anger and doubting.\"\nComplex word: pray\nComplexity level of the complex word: 0.125\n\nSource text: bible\nSentence: \"Before Ephraim and Benjamin and Manasseh, stir up your might!\"\nComplex word: Ephraim\nComplexity level of the complex word: 0.5\n\n[Response]\n\nSource text: @recurso\nSentence: @oracion\nComplex word: @aEvaluar\nComplexity level of the complex word: [Response]",
        "prompt_diff_source_legalEC": "Instructions: This is a complex word classification task and there is a set of texts from different subjects in Law Studies in Ecuatorian Spanish, each text contains one complex word. Your task is to generate the level of complexity of the complex word in each text on a scale of 0 to 1, where 0 indicates that the word is very easy and 1 indicates that the word is very difficult.\n\nExample:\n\nSubject:  Mediación escolar en la prevención de episodios de violencia escolar en el primer curso de bachillerato\nSentence: \"Para el ejercicio de los derechos y las garantías constitucionales no se exigirán condiciones o requisitos que no estén establecidos en la Constitución o la ley \"\nComplex word: requisitos\nComplexity level of the complex word: 0.0\n\nSource text: analisis de carnet de discapacidad\nSentence: \"8 numeral 2 dispone el sustento de diversos valores para vivir bien \"\nComplex word: sustento\nComplexity level of the complex word: 0.0\n\nSource text: Necesidad de implementar la mediacion como medio alternativo para la solución de conflictos\nSentence: \"Es de procedencia Chorotega, que con el transcurrir del tiempo, al igual que ha ocurrido con otros pueblos, cambió su nombre primitivo, que debió ser Xipixapa o Tipitapa \"\nComplex word: Chorotega\nComplexity level of the complex word: 0.33\n\nSource text: nivel basico - carrera derecho TEXTO  00078  DERECHO  DE LA COMUNIDAD\nSentence: \"Mantener la posesión de las tierras y territorios ancestrales y obtener su adjudicación gratuita\"   \nComplex word: adjudicación\nComplexity level of the complex word: 0.44\n\nSource text: Mediación escolar en la prevención de episosodios de violencia escolar en el primer curso de bachillerato\nSentence: \"Como es la resolución de problemas interpersonales entre los integrantes de los grupos humanos que han tenido transcendencia muy remota \"\nComplex word: transcendencia\nComplexity level of the complex word: 5.6\n\nSource text:  Necesidad deimplementar la mediacion como medio alternativo para la solución de conflictos\nSentence: \"De esa manera dan vida a la UPOCAM, la unión Provincial de Organizaciones campesinas de Manabí\"\nComplex word: UPOCAM\nComplexity level of the complex word: 0.67\n\nSource text: Aplicación de los métodos alternativos de resolución de conflictos en el Centro de Educación Básica Cecilia\nSentence: \"Los conflictos entre países limítrofes en geografía \"\nComplex word: condiscípulos\nComplexity level of the complex word: 0.78\n\nSource text: TESIS\nSentence: \"No puede estipularse proindivisión por más de cinco años; pero cumplido este término podrá renovarse el pacto  \"\nComplex word: proindivisión\nComplexity level of the complex word: 0.89\n\n[Response]\n\nSource text: @recurso\nSentence: @oracion\nComplex word: @aEvaluar\nComplexity level of the complex word: [Response]",
        "prompt_diff_source_AdminLex": "Instructions: This is a complex word classification task and there is a set of texts from different subjects in public documents of Ecuador, each text contains one complex word. Your task is to generate the level of complexity of the complex word in each text on a scale of 0 to 1, where 0 indicates that the word is very easy and 1 indicates that the word is very difficult.\n\nExample:\n\nSubject:  FACTURACION ELECTRONICA\nSentence: \"FACTURACION ELECTRONICA Previo a la solicitud de autorización que debe realizar ante el SRI para emitir comprobantes de forma electrónica, asegúrese de contar con \"\nComplex word: autorización\nComplexity level of the complex word: 0.33\n\nSource text: DEVOLUCION AUTOMATICA DE IVA A PERSONAS ADULTAS MAYORES\nSentence: \"DEVOLUCION AUTOMATICA DE IVA A PERSONAS ADULTAS MAYORES Digite el número de cédula del beneficiario en el campo RUC / CI / Pasaporte y la clave de SRI en línea  \"\nComplex word: digite\nComplexity level of the complex word: 0.33\n\nSource text: AUTORIZACIÓN A TERCEROS EN LÍNEA\nSentence: \"AUTORIZACIÓN A TERCEROS EN LÍNEA ISD (Exoneraciones por enfermedad catastrófica y estudios en el exterior) \"\nComplex word: catastrófica\nComplexity level of the complex word: 0.67\n\nSource text: CODIGO MUNICIPAL\nSentence: \"CODIGO MUNICIPAL En todo caso, se privilegiará la difusión de este Código y el mayor conocimiento de sus normas por los habitantes del Distrito Metropolitano \"   \nComplex word: difusión\nComplexity level of the complex word: 0.67\n\nSource text: GUIA DE DEVOLUCION DEL IVA - AULTO MAYOR \nSentence: \"GUIA DE DEVOLUCION DEL IVA - AULTO MAYOR Obtener en las oficinas del SRI la clave de acceso a SRI en Línea al suscribir el acuerdode responsabilidad para uso de medios electrónicos  \"\nComplex word: suscribir\nComplexity level of the complex word: 1\n\nSource text:  GUIA DE ANULACION DE COMPROBANTES ELECTRONICOS\nSentence: \"GUIA DE ANULACION DE COMPROBANTES ELECTRONICOS Solicitud de anulación de comprobantes electrónicos por parte del emisor \"\nComplex word: emisor\nComplexity level of the complex word: 1\n\n[Response]\n\nSource text: @recurso\nSentence: @oracion\nComplex word: @aEvaluar\nComplexity level of the complex word: [Response]"
    }
    prompt_use = "prompt_diff_source_AdminLex"

    # print( prompt.get(prompt_use))

    df = pd.read_excel(file_corpus_train)
    # df.loc[df["token"].isnull(), "token"] = "null"
    datos = df.loc[minimo:maximo, ["id", "Context", "Sentencia", "Palabra", "Nivel de Complejidad", "Escala"]]
    datos.columns = ["id", "source", "sentence", "token", "complexity", "escala"]
    key = os.getenv("API_KEY")
    gpt = Gpt3(datos, prompt.get(prompt_use), key, load=args.load, chatgpt=False)
    # # calcular_total_pagar(prompt, datos, cost=0.03)
    gpt.process_all(file_path=file_corpus_train, save_result=True, percent=args.percent, result_name=f"{prompt_use} final")